### ISSUE TITLE
question about RFNoC:PDU TX

### ISSUE THREAD

**Issue by heatonhfg** [EttusResearch/gr-ettus#35] opened 2019-03-28 14:06 UTC
Hi, can anyone give me a example about using RFNoC:PDU TX and RFNoC:PDU RX module?

**Comment by natetemple** [comment] 2019-08-14 16:56
@heatonhfg I'm going to close this issue as it is not a bug report. For support questions, please email us at support@ettus.com.

**Closed by natetemple** 2019-08-14 16:56 UTC
