### ISSUE TITLE
with Gnuradio 3.8.1 and   UHD_4.1.0.4-0 it has errors

### ISSUE THREAD

**Issue by stackprogramer** [EttusResearch/gr-ettus#59] opened 2021-12-18 19:16 UTC
when I want to install gr-ettus  i faced with errors...
with Gnuradio 3.8.1 and   UHD_4.1.0.4-0 it has errors
Ubuntu 20.04
any offer?
```
[ 64%] Swig source ettus_swig.i
Deprecated command line option: -modern. This option is now always on.
/home/sp/Documents/gr-ettus-1038c4ce5135a2803b53554fc4971fe3de747d9a/swig/ettus_swig.i:140: Error: Template 'set_property' undefined.
/home/sp/Documents/gr-ettus-1038c4ce5135a2803b53554fc4971fe3de747d9a/swig/ettus_swig.i:141: Error: Template 'set_property' undefined.
/home/sp/Documents/gr-ettus-1038c4ce5135a2803b53554fc4971fe3de747d9a/swig/ettus_swig.i:142: Error: Template 'set_property' undefined.
/home/sp/Documents/gr-ettus-1038c4ce5135a2803b53554fc4971fe3de747d9a/swig/ettus_swig.i:143: Error: Template 'set_property' undefined.
/home/sp/Documents/gr-ettus-1038c4ce5135a2803b53554fc4971fe3de747d9a/swig/ettus_swig.i:145: Error: Template 'get_property' undefined.
/home/sp/Documents/gr-ettus-1038c4ce5135a2803b53554fc4971fe3de747d9a/swig/ettus_swig.i:146: Error: Template 'get_property' undefined.
/home/sp/Documents/gr-ettus-1038c4ce5135a2803b53554fc4971fe3de747d9a/swig/ettus_swig.i:147: Error: Template 'get_property' undefined.
/home/sp/Documents/gr-ettus-1038c4ce5135a2803b53554fc4971fe3de747d9a/swig/ettus_swig.i:148: Error: Template 'get_property' undefined.
/usr/local/include/uhd/types/dict.hpp:145: Warning 503: Can't wrap 'operator std::map<std::string,std::string>' unless renamed to a valid identifier.
make[2]: *** [swig/CMakeFiles/ettus_swig_swig_compilation.dir/build.make:65: swig/CMakeFiles/ettus_swig.dir/ettus_swigPYTHON.stamp] Error 8
make[2]: *** Deleting file 'swig/CMakeFiles/ettus_swig.dir/ettus_swigPYTHON.stamp'
make[1]: *** [CMakeFiles/Makefile2:421: swig/CMakeFiles/ettus_swig_swig_compilation.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

```

**Comment by stackprogramer** [comment] 2021-12-19 08:36
I too tested with UHD 4.0 i have same before error, how can i solve this erros..

**Comment by mbr0wn** [comment] 2022-10-24 15:01
I cannot reproduce this. Closing.

**Closed by mbr0wn** 2022-10-24 15:01 UTC
