### ISSUE TITLE
cmake unable to find module "mpir"

### ISSUE THREAD

**Issue by cyberphox** [EttusResearch/gr-ettus#50] opened 2020-11-06 16:06 UTC
I am having some trouble with cmake, see the log below:

cmake -DENABLE_QT=True ../
-- Build type not specified: defaulting to release.
-- Checking for module 'mpir >= 3.0'
--   No package 'mpir' found
-- Could NOT find MPIR (missing: MPIRXX_LIBRARY MPIR_LIBRARY MPIR_INCLUDE_DIR) 
-- User set python executable /usr/bin/python3
-- Extracting version information from git describe...
CMake Error at /usr/local/lib/cmake/gnuradio/FindUHD.cmake:97 (message):
  The found UHD version (3.15.0.HEAD-0-g4e06022c) is not compatible with the
  version required (4.0).
Call Stack (most recent call first):
  CMakeLists.txt:98 (find_package)

**Comment by michaelld** [comment] 2020-11-06 17:23
@cyberphox  the issue is not with MPIR; it is that the UHD found is version 3.15 while the version required is 4.0.

**Comment by michaelld** [comment] 2020-11-06 17:25
gr-ettus builds fine with the correct dependencies installed; as such I'm closing this issue. I'd strongly suggest if you continue to have issues then get on the USRP list < https://lists.ettus.com/mailman/listinfo/usrp-users_lists.ettus.com > and send an email to it. There are folks there who can help you. Good luck!

**Closed by michaelld** 2020-11-06 17:25 UTC
